### ISSUE TITLE
charset metatag doesn't work

### ISSUE THREAD

**Issue by Secretmapper** [venmo/react-html-document#9]
Inserting the charset metatag doesn't add it to the compiled html:

```
  <HTMLDocument
    metatags={[
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' }
    ]}
  >
```

**Comment by xavierelopez** [comment]
Hey @Secretmapper, thanks for the example. Please try using camel case `charSet` instead of `charset`, as that's what React [officially supports](https://facebook.github.io/react/docs/tags-and-attributes.html#html-attributes).

**Comment by Secretmapper** [comment]
Just chiming in to say `charSet` works as intended, didn't know React remapped it. Thanks!
